/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectDocumentRouteImport } from './routes/project-document'
import { Route as ProjectReportRouteImport } from './routes/project-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDocumentRoute = ProjectDocumentRouteImport.update({
  id: '/project-document',
  path: '/project-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectReportRoute = ProjectReportRouteImport.update({
  id: '/project-report',
  path: '/project-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project-document': typeof ProjectDocumentRoute
  '/project-report': typeof ProjectReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project-document': typeof ProjectDocumentRoute
  '/project-report': typeof ProjectReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project-document': typeof ProjectDocumentRoute
  '/project-report': typeof ProjectReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project-document' | '/project-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project-document' | '/project-report'
  id: '__root__' | '/' | '/project-document' | '/project-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectDocumentRoute: typeof ProjectDocumentRoute
  ProjectReportRoute: typeof ProjectReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-document': {
      id: '/project-document'
      path: '/project-document'
      fullPath: '/project-document'
      preLoaderRoute: typeof ProjectDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-report': {
      id: '/project-report'
      path: '/project-report'
      fullPath: '/project-report'
      preLoaderRoute: typeof ProjectReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectDocumentRoute: ProjectDocumentRoute,
  ProjectReportRoute: ProjectReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
